java:
  label: Java
  permalink: /java
  description: Java
spring:
  label: Spring
  permalink: /spring
  description: Spring Boot
database:
  label: Database
  permalink: /database
  description: Database
jpa:
  label: JPA
  permalink: /jpa
  description: Java Persistence API
cicd:
  label: CI/CD
  permalink: /cicd
  description: CI/CD Pileline
github-action:
  label: Github Action
  permalink: /github-action
  description: Github Action CI/CD